### ISSUE TITLE
Support for React.js and others (Angular ...)

### ISSUE THREAD

**Issue by tgdn** [kapetan/titlebar#10]
First, well done for this awesome thing. Although it would be very useful if there would be support for React.js

**Comment by wing-kai** [comment]
@tgdn https://github.com/wing-kai/react-titlebar

**Comment by tgdn** [comment]
Thank you @wing-kai 
I did one of my one but yours has many more features https://github.com/tgdn/titlebar-react

**Comment by kapetan** [comment]
Cool. Both modules look good. People can use your modules if they want React intergration.
