### ISSUE TITLE
created element is not a DOM node

### ISSUE THREAD

**Issue by yoshuawuyts** [kapetan/titlebar#4]
The exposed element by `titlebar()` is not a DOM node:

![screen shot 2015-05-29 at 15 19 05](https://cloud.githubusercontent.com/assets/2467194/7883521/6f7d3a84-0617-11e5-9aea-ee14314dc64e.png)

This works fine with older methods such as `Node.appendChild()`, but newer methods like `Node.insertBefore()` don't like this.

I suspect the root issue is that the prototype is being overwritten, since `domify` returns proper DOM nodes. Thanks!

**Comment by yoshuawuyts** [comment]
Welp, apparently I should read code before opening an issue. - https://github.com/kapetan/titlebar/blob/master/index.js#L58-L70

Would be neat if the exposed element inherited from `HTMLElement` though, though I'm not sure how it'll play with the custom CSS like on `titlebar.appendTo()`.

**Comment by kapetan** [comment]
I don't know if that's easily possible. For now I've added the `element` property to the readme.

**Comment by yoshuawuyts** [comment]
I can solve it for my own project by wrapping it in a custom element, which is a higher abstraction level. It does require a using a webcomponents polyfill, so I think it's better to have that live in a separate repo.
