### ISSUE TITLE
method to set title

### ISSUE THREAD

**Issue by dylang** [kapetan/titlebar#7]
I chuckled when I realized the module called "titlebar" doesn't have the ability to show the _title_. :smirk:

**Comment by kapetan** [comment]
What I've previously done is to append html to the root element of the titlebar and added some css to position it. E.g. in my [repaint-shell](https://github.com/kapetan/repaint-shell/blob/master/index.js#L96) project I add a search field to the titlebar (similar to safari address bar). The same could be done to add a title to **title**-bar:

``` js
var titlebar = require('titlebar')();
titlebar.appendTo('#container');

var div = document.createElement('div');
div.innerHTML = 'My title';
div.id = 'title';
titlebar.element.appendChild(div);
```

``` css
#title {
  text-align: center;
  padding-top: 4px;
}
```
