### ISSUE TITLE
hooks for doing chrome-style titlebar

### ISSUE THREAD

**Issue by dylang** [kapetan/titlebar#8]
I don't expect this module to support Chrome-style titlebar tabs, but it would be nice if this had the hooks for a third party module to provide tabs. It might just be a DOM node exposed for adding content to and some CSS so the tabs don't interfere with the buttons. Also dragging the tabs should not move the window in Electron.

_For the curious, I haven't found a good implementation of Chrome-style tabs in JS yet. I easily added [Angular Material Tabs](https://material.angularjs.org/latest/#/demo/material.components.tabs) to my app but I'm thinking about trying [react-draggable-tab](https://github.com/georgeOsdDev/react-draggable-tab) because it already has drag-and-drop support._

**Comment by kapetan** [comment]
There is `titlebar.element` which exposes the root element of the titlebar. You can always append html to that and use css to position it.

I haven't used it my self, but there is a project which tries to replicate chrome tabs in html and css: [adamschwartz/chrome-tabs](https://github.com/adamschwartz/chrome-tabs).
